#Application Configuration
app.api.key=${APP_API_KEY:your-default-dev-key}
app.database.directory=${APP_DATABASE_DIRECTORY:${user.dir}/data}

#Web Server Configuration
server.port=${SERVER_PORT:8080}

# Set default log level
logging.level.root=info
# Set log level for your application package
logging.level.dev.ikm.aperture=debug